config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :jobs
  resources :users, only: [:index, :show]

  resources :jobs do
    resources :applies
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    alias_action :create, :read, :update, :destroy, to: :crud

    if user.admin?
      can :manage, :all
    end
    can :crud, User, user_id: user.id



    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :skills, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  # validates :resume, presence: true

  has_attached_file :resume, styles: {icon: "100x100>"}
  validates_attachment_content_type :resume, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.template) }
  has_attached_file :cover_letter, styles: {icon: "100x100>"}
  validates_attachment_content_type :cover_letter, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.template) }

  belongs_to :user
  belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :location, presence: true
  validates :job_type, presence: true
  validates :compensation, presence: true
  validates :description, presence: true
  validates :skills, presence: true

  has_many :applies
  has_many :users, through: :applies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  has_attached_file :resume
  validates_attachment_content_type :resume, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :cover_letter
  validates_attachment_content_type :cover_letter, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.template) }

  has_many :applies
  has_many :jobs, through: :applies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :skills, :admin, :street_address, :city, :state, :zip_code, :phone_carrier, :resume, :cover_letter])
  end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  def new
    @job = Job.find(params[:job_id])
    @apply = @job.applies.new
  end

  def create
    @job = Job.find(params[:job_id])
    @apply = @job.applies.new(apply_params)
    if @job.save
      flash[:notice] = 'Application Submitted!'
      redirect_to job_path(@job)
    else
      flash[:alert] = 'Your application was not submitted.'
      render :new
    end
  end

private
  def apply_params
    params.require(:apply).permit(:first_name, :last_name, :email, :phone_number, :skills, :street_address, :city, :state, :zip_code, :resume, :cover_letter, :job_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    ExampleMailer.email(User.where(admin: true)).deliver
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    authorize! :new, @job
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = 'Job Saved!'
      redirect_to jobs_path
    else
      flash[:alert] = "Job not saved."
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
    authorize! :edit, @job
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = 'Job Updated!'
      redirect_to job_path(@job)
    else
      flash[:alert] = "Job not saved."
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

private
  def job_params
    params.require(:job).permit(:title, :location, :job_type, :description, :compensation, :duration, :skills)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize! :read, @users
  end

  def show
    @user = User.find(params[:id])
    # authorize! :crud, @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applies/_form.html.erb
<%= render "layouts/errors", :object => @apply %>

<div class="application-job">
  <div class="container app-form">
    <div class="row">
      <%= form_for [@job, @apply] do |f| %>
      <div class="card application-card">
        <div class="apply input-field col s6">
          <%= f.label :'First Name', :class => 'active' %><br />
          <%= f.text_field :first_name, autofocus: true %>
        </div>

        <div class="apply input-field col s6">
          <%= f.label :'Last Name', :class => 'active' %><br />
          <%= f.text_field :last_name, autofocus: true %>
        </div>
      </div>

      <div class="card application-card">
        <div class="apply input-field col s3">
          <%= f.label :'Street Address', :class => 'active' %><br />
          <%= f.text_field :street_address, autofocus: true %>
        </div>

        <div class="apply input-field col s3">
          <%= f.label :'City', :class => 'active' %><br />
          <%= f.text_field :city, autofocus: true %>
        </div>

        <div class="apply input-field col s3">
          <%= f.label :'State', :class => 'active' %><br />
          <%= f.text_field :state, autofocus: true %>
        </div>

        <div class="apply input-field col s3">
          <%= f.label :'Zip Code', :class => 'active' %><br />
          <%= f.text_field :zip_code, autofocus: true %>
        </div>
      </div>

      <div class="card application-card">
        <div class="apply input-field col s12">
          <%= f.text_field :skills, :class => 'autocomplete' %>
          <%= f.label :skills, :class => 'active' %><br />
        </div>
      </div>

      <div class="card application-card">
        <div class="apply input-field col s6">
          <%= f.label :'Phone Number', :class => 'active' %><br />
          <%= f.text_field :phone_number, autofocus: true %>
        </div>

        <div class="apply input-field col s6">
          <%= f.label :email, :class => 'active' %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>
      </div>

      <div class="card application-card">
        <div class="file-field apply input-field col s6 file-upload">
          <div class="btn">
            <span>Resume <i class="fa fa-file-pdf-o" aria-hidden="true"></i></span>
            <%= f.file_field :resume %>
          </div>
          <div class="file-path-wrapper">
            <input type="text" class="file-path validate">
          </div>
        </div>

        <div class="file-field apply input-field col s6 file-upload">
          <div class="btn">
            <span>Cover Letter <i class="fa fa-file-word-o" aria-hidden="true"></i></span>
            <%= f.file_field :cover_letter %>
          </div>
          <div class="file-path-wrapper">
            <input type="text" class="file-path validate">
          </div>
        </div>
      </div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :job_id, :value => @job.id %>

      <div class="actions col s12">
        <%= f.submit "Apply", :class => 'btn'%>
      </div>
      <%end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="splash">
  <div class="image-column"></div>
  <div class="welcome">
    <h3 class="center welcome-title">Bridging The Gap For Professionals.</h3>
    <br>
    <h3 class="center welcome-connect">Contract <span>|</span> Temp To Hire <span>|</span> Direct Hire</h3>
  </div>
</div>
<div class="row industries-row">
  <h1 class="center " id="we-serve">Industries We Serve</h1>
  <div class="col m12 l4" id='industry-column'>
    <div class="card industry-card">
      <h4 class="center-align industry-titles" id="tech-title">Technology</h4>
      <div class="col s4 offset-s4 underline"></div>
      <p class="center-align industry-info" id="tech-info">Our recruiting staff has been serving the tech community for over 20 years. We work closely with many companies, from Intel to fresh startups.</p>
    </div>
  </div>
  <div class="col m12 l4">
    <div class="card industry-card">
      <h4 class="center-align industry-titles" id="hr-title">Human Resources</h4>
      <div class="col s4 offset-s4 l8 offset-l2 underline2"></div>
      <p class="center-align industry-info" id="hr-info">Our staff has a very strong background in HR consulting and recruiting. We understand what it takes to assure best practices in the workplace.</p>
    </div>
  </div>
  <div class="col m12 l4">
    <div class="card industry-card acct-card">
      <h4 class="center-align industry-titles" id="accounting-title">Accounting</h4>
      <div class="col s4 offset-s4 underline"></div>
      <p class="center-align industry-info" id="accounting-info">Our staff wants to connect you with a team that understands your importance. We will help you find the right position for you.</p>
    </div>
  </div>
</div>
<div class="row" id="footer">

</div>

app/views/jobs/_form.html.erb
<div class="errors">
  <%= render "layouts/errors", :object => @job %>
</div>
<div class="new-job">
  <div class="container">
    <div class="card new-job-card">
      <div class="row">
        <div class="job-form row" data-role='page'>
          <div class="col s12">
            <%= form_for @job do |f| %>
            <div class="input-field col s8 offset-s2 form-input">
              <%= f.label :title %>
              <%= f.text_field :title %>
            </div>
            <div class="input-field col s8 offset-s2 form-input">
              <%= f.label :location %>
              <%= f.text_field :location %>
            </div>
            <div class="col s8 offset-s2 radio-buttons">
              <%= f.radio_button :job_type, 'Contract' %>
              <%= f.label :job_type_contract, 'Contract' %>
              <%= f.radio_button :job_type, 'Temp to Hire' %>
              <%= f.label :job_type_temp_to_hire, 'Temp to Hire' %>
              <%= f.radio_button :job_type, 'Direct Hire' %>
              <%= f.label :job_type_direct_hire, 'Direct Hire' %>
            </div>
            <div class="input-field col s8 offset-s2 form-input" id='duration_field'>
              <%= f.label :duration %>
              <%= f.text_field :duration %>
            </div>
            <div class="input-field col s8 offset-s2 form-input">
              <%= f.label :compensation %>
              <%= f.text_field :compensation %>
            </div>
            <div class="input-field col s8 offset-s2 form-input">
              <%= f.label :'skills_(comma separated)' %>
              <%= f.text_field :skills, :class => 'autocomplete' %>
            </div>
            <div class="input-field col s8 offset-s2 form-input">
              <%= f.label :description %>
              <%= f.text_area :description, :class => 'materialize-textarea' %>
            </div>
            <div class="col s12">
              <%= f.submit 'Submit', :class => 'btn btn-default view-button' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="splash">
  <div class="image-column"></div>
  <div class="welcome">
    <h3 class="center welcome-title">Jobs Await!</h3>
    <br>
    <h3 class="center welcome-connect">Let's get you into a position that fits you.</h3>
  </div>
</div>

<div class="row outlook-row">
  <div class="container">
    <h2 id="job-outlook">Job Outlook</h2>
    <div class="col s12 m4 job-outlook-column">
      <p class="headers"><strong>Portland</strong></p>
      <p class='outlook-info'>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae voluptatum magni eaque quae ullam dolorum!
      </p>
    </div>
    <div class="col s12 m4 job-outlook-column">
      <p class="headers"><strong>Vancouver</strong></p>
      <p class='outlook-info'>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae voluptatum magni eaque quae ullam dolorum!
      </p>
    </div>
    <div class="col s12 m4 job-outlook-column">
      <p class="headers"><strong>Eugene</strong></p>
      <p class='outlook-info'>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae voluptatum magni eaque quae ullam dolorum!
      </p>
    </div>
  </div>
</div>
<div class="row jobs-row">
  <div class="container">
    <div class="col s12">
      <h2 id="job-list-title">Job Listing</h2>
      <% if @jobs.any? %>
      <% @jobs.each do |job| %>
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header">
            <p id="first-head"><%= job.title %></p><br>
            <p id="second-head"><%= job.job_type %> | <%= job.location %></p>
          </div>
          <div class="collapsible-body">
            <p class='compensation-p'>Compensation: $<%= job.compensation %></p><br>
            <% if job.duration != '' %>
            <p>Duration: <%= job.duration %></p><br>
            <% end %>
            <p>Requirements: <%= job.skills %></p><br>
            <%= link_to 'View Job', job_path(job), :class => 'btn btn-default view-button' %>
          </div>
        </li>
      </ul>
      <% end %>
      <% else %>
      <div class="row no-jobs">
        <div class="col s8 offset-s2 ">
          <div class="card job-card">
            <h2 id='no-job-title'>There are currently no job postings</h2>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
<div class="job-detail">
  <div class="row job-detail-row">
    <div class="col s8 offset-s2 ">
      <div class="card job-card">
        <h2 class="center detail-title"><%= @job.title %></h2>
        <br>
        <h3 class='center detail-location'><%= @job.location %></h3>
        <br>
        <h4 class="center detail-job_type"><%= @job.job_type%></h4>
        <br>
        <% if @job.duration != '' %>
        <h5 class="center detail-duration"><%= @job.duration %></h5>
        <% end %>
        <br>
        <h4 class="center detail-compensation">$<%= @job.compensation %></h4>
        <br>
        <h5 class="detail-skills"><strong>Requirements:</strong> <%= @job.skills %></h5>
        <br>
        <h5 class="detail-description-head"><strong>Description:</strong></h5>
        <br>
        <h5 class="detail-description"><%= @job.description %></h5>
        <% if can? :edit, Job %>
        <%= link_to 'Edit Job', edit_job_path(@job), :class => 'btn btn view-button' %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to 'Apply!', new_job_apply_path(@job), :class => 'btn view-button' %>
        <% end %>
      </div>
    </div>
  </div>

<div class="row">
  <% if user_signed_in?  %>
  <% if current_user.admin? %>
  <% if !@job.users.any? %>
  <h2 class="center no-applicants">There are no applicants for this job.</h2>
  <% else %>
  <div class="row">
    <div class="col s8 offset-s2 user-table">
      <h2 class="center applicants">Applicants</h2>
      <table class="table striped bordered">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone Number</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% @job.users.each do |user|%>
          <tr data-link='<%= user_path(user) %>' class = 'table-rows'>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.phone_number %></td>
            <td><%= user.email %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>
  <% end %>
  <% end %>
</div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello Recruit</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="my-nav">
      <%= link_to 'HelloRecruit', root_path, :id => 'hello-header' %>
      <% if !user_signed_in? %>
        <li class='nav-links'><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li class='nav-links'><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
      <li class='nav-links'><%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %></li>
      <li class='nav-links'><%= link_to 'Profile', user_path(current_user) %></li>
        <% if can? :manage, :all %>
          <li class='nav-links'><%= link_to 'Candidates', users_path %></li>
          <li class='nav-links'><%= link_to 'Add Job', new_job_path %></li>
        <% end %>
      <% end %>
      <li class='nav-links'><%= link_to 'Jobs', jobs_path %></li>
    </div>
    <%= yield %>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Hello Recruit</h5>
            <p class="grey-text text-lighten-4">Established in 2017, we pride ourselves on the connections we have and the ones we continue to make. Be sure to follow us on Twitter, Facebook, and LinkedIn</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Contact Us</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!"><i class="fa canter-align fa-facebook-square" aria-hidden="true"></i></a></li>
              <li><a class="grey-text text-lighten-3" href="#!"><i class="fa canter-align fa-twitter-square" aria-hidden="true"></i></a></li>
              <li><a class="grey-text text-lighten-3" href="#!"><i class="fa canter-align fa-linkedin-square" aria-hidden="true"></i></a></li>
              <li><a class="grey-text text-lighten-3" href="#!"><i class="fa canter-align fa-envelope-open" aria-hidden="true"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container copy">
        &copy; 2017 Hello Recruit
        <a class="grey-text text-lighten-4 right" href="#!">Privacy Policy</a>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $('.dropdown-button').dropdown({
        hover: false
      });
      $("#job_job_type_contract").click(function() {
        $('#duration_field').slideDown();
      });
      $("#job_job_type_temp_to_hire").click(function() {
        $('#duration_field').slideUp();
        $('input#job_duration').val('');
      });
      $("#job_job_type_direct_hire").click(function() {
        $('#duration_field').slideUp();
        $('input#job_duration').val('');
      });
      $("tr[data-link]").click(function() {
        window.location = this.dataset.link;
      });
      var availableSkills = [
        "HR",
        "Git",
        "Bash",
        "Management",
        "Ruby",
        "Ruby on Rails",
        "JavaScript"
      ];
      $('input.autocomplete').autocomplete({
        source: availableSkills,
        multiple: {
          enable: true,
          maxSize: 10
        },
        limit: 20
      });
      $(window).scroll(function() { // check if scroll event happened
        if ($(document).scrollTop() > 50) {
          $(".my-nav").css({
            'transition': 'background-color 2s ease',
            "background-color": "rgb(51, 58, 86)"
          });
        } else {
          $(".my-nav").css("background-color", "rgba(51, 58, 86, 0.8)");
        }
      });
    </script>
  </body>
</html>

app/views/users/index.html.erb
<div class="candidates">
  <div class="container">
    <% if !@users.any? %>
    <div class="row no-users">
      <div class="col s8 offset-s2 ">
        <div class="card">
          <h2>There are currently no candidates.</h2>
        </div>
      </div>
    </div>
    <% else %>
      <div class="row candidate-table">
        <h2 class="candidates-list center">Candidate List</h2>
        <div class="col s12 user-table">
          <table class="table hover striped bordered">
            <thead>
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user|%>
                <tr data-link='<%= user_path(user)%>' class = 'table-rows' >
                  <td><%= user.first_name %></td>
                  <td><%= user.last_name %></td>
                  <td><%= user.phone_number %></td>
                  <td><%= user.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="row profile-row">
  <div class="card profile-card">
      <div class="col s10 offset-s1">
        <% if current_user.id === @user.id %>
          <h4 class="card-title center"><%= @user.first_name %> <%= @user.last_name %><%= link_to edit_user_registration_path do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %></h4>
        <% else %>
          <h4 class="card-title center"><%= @user.first_name %> <%= @user.last_name %></h4>
        <% end %>
        <p class="user-email left-align">Email: <%= @user.email %></p>
        <p class="user-phone_number left-align">Phone number: <%= @user.phone_number %></p>
        <p class="user-street_address left-align">Street Address: <%= @user.street_address %></p>
        <p class="user-city-state left-align">City/State: <%= @user.city %>, <%= @user.state %></p>
        <p class="user-zip_code left-align">Zip Code: <%= @user.zip_code %></p>
        <p class="user-skills left-align">Listed Skills: <%= @user.skills %></p>
        <%= link_to 'Resume', @user.resume.url, target: '_blank', :class => 'doc-links' %>
        <%= link_to 'Cover Letter', @user.cover_letter.url, target: '_blank', :class => 'doc-links' %>
      </div>
    </div>
  </div>
  <div class="row applied-row">
    <div class="col s10 offset-s1">
      <% if !@user.jobs.any? %>
        <h2 class="center no-applies">You have not applied for any jobs.</h2>
      <% else %>
        <div class="col s8 offset-s2 user-table">
          <h2 class="applies">Jobs Applied For</h2>
          <table class="table striped bordered">
            <thead>
              <tr>
                <th>Job Title</th>
                <th>Location</th>
                <th>Job Type</th>
                <th>Compensation</th>
              </tr>
            </thead>
            <tbody>
              <% @user.jobs.each do |job|%>
              <tr data-link='<%= job_path(job) %>' class = 'table-rows'>
                <td><%= job.title %></td>
                <td><%= job.location %></td>
                <td><%= job.job_type %></td>
                <td>$<%= job.compensation %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>